name: C++ CMake Conan Build

on:
  workflow_call:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            preset: release
          - os: windows-latest
            preset: release
          - os: macos-latest
            preset: release

    runs-on: ${{ matrix.os }}

    steps:
      - name: Setup
        uses: tnt-coders/ci-workflows/.github/actions/cpp-cmake-conan-setup@master

      - name: Configure
        run: cmake --preset ${{ matrix.preset }}

      - name: Build
        run: cmake --build --preset ${{ matrix.preset }}

      - name: Lint
        if: hashFiles('.clang-tidy') != ''
        run: cmake --build build/${{ matrix.preset }} --target clang-tidy

      - name: Test
        run: ctest --preset ${{ matrix.preset }} --output-on-failure
